### ISSUE TITLE
Attempting to fix AfterFunc is a mistake

### ISSUE THREAD

**Issue by snaury** [desertbit/timer#1]
While `time.NewTimer` and `Timer.Reset` in package `time` have an unfortunate side-effect due to using a non-blocking send, there's no such problem with `time.AfterFunc`, i.e. when `Timer.Reset` returns `false` it means timer has either already fired (and `f` will be called eventually) or stopped by the user. Attempting to fix `AfterFunc` with locks is a mistake, `AfterFunc` is not broken, and `Reset` already behaves as if `Stop` and a new `time.AfterFunc` have been called atomically.

**Comment by r0l1** [comment]
True. Thanks for the feedback!
